### ISSUE TITLE
xml parser

### ISSUE THREAD

**Issue by mathieudutour** [skpm/sketch-polyfill-fetch#1]
https://github.com/mathieudutour/sketch-module-fetch-polyfill/blob/master/lib/index.js#L47

**Comment by darknoon** [comment]
It seems in the `fetch()` API, they are suggesting to use a DOMParser directly, so I don't think we should include it here.

**Comment by mathieudutour** [comment]
Oh you are right, I assume it was since it's in unfetch https://github.com/developit/unfetch/blob/master/src/index.js#L43
