### ISSUE TITLE
Fetch crashes Sketch v47.1

### ISSUE THREAD

**Issue by damianprzygodzki** [skpm/sketch-polyfill-fetch#11]
Probably after some update, polyfill stopped working and crashes my sketch.

Steps to reproduce:
1) `skpm create test`
2) 
```
export default function(context) {
    fetch("https://google.com")
      .then(response => response.text())
      .then(text => log(text);
}
```
3) Crash!

**Comment by mathieudutour** [comment]
any log?
If that's the exact code you are using, it's missing a `)`: `.then(text => log(text))`
