### ISSUE TITLE
FormData and fetch do not work

### ISSUE THREAD

**Issue by konsalex** [skpm/sketch-polyfill-fetch#20]
Hello there.

A weird error occurs to a plugin I started developing.

I try to send a POST request to a localserver. Below is the code

```
console.log("Starting the FormData");
const formData = new FormData();
console.log("Starting the Fetching");
fetch("https://127.0.0.1:5000/api", {
method: "POST",
body: formData
})
.then(res => {
console.log(res);
})
.catch(err => {
console.log(err);
});
});
console.log("Finished");
```
The thing is that the console prints "Starting ..." but when I create the FormData the plugin stops there and doesn't log anything at all so the "Starting the Fetching" and the last print do not get printed at all.

Any clue?

P.S. : I created the plugin with skpm (0.4.2) 2 days ago and the OS is Mojave.

**Comment by mathieudutour** [comment]
not sure if it's a copy paste typo but there is an extra `});` on the second to last line.

I just tried running `skpm create test` and copy pasting your code (without the typo) in the `export default function` and it works fine.

`@skpm/builder` is on version 0.7 tho, the version `0.4.2` is really old. I'd recommend you update it and see it fixes it.

**Comment by konsalex** [comment]
You were right! I cannot find a reason for the @skpm/builder to be 0.4.2 when 0.7 is out but nevertheless thank you very much @mathieudutour .
