### ISSUE TITLE
statusText returns NSString rather than Javascript string

### ISSUE THREAD

**Issue by jasim** [skpm/sketch-polyfill-fetch#22]
Application code need to cast `statusText` explicitly into `String` for use in Javascript land. This can go unnoticed because `log` seems to cast everything into string. However `JSON.stringify` fails on NSString. 

See: https://github.com/jasim/skpm_fetch_test/blob/master/src/my-command.js#L23

If you clone the repo and run it, you'll see `{}` where `JSON.stringify` is logged.

Casting to `String()` in https://github.com/skpm/sketch-polyfill-fetch/blob/master/lib/index.js#L25 should fix it

**Comment by mathieudutour** [comment]
Ah yep, good catch 👍

Should be fixed in 0.4.6
