### ISSUE TITLE
NSURLRequest sends cookies by default

### ISSUE THREAD

**Issue by kannonboy** [skpm/sketch-polyfill-fetch#7]
Not necessarily a problem, but possibly unexpected for a `fetch` polyfill, as `fetch` in the browser [doesn't send cookies by default](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch). 

Clients can override this behaviour by passing an empty `Cookie` header, but I think it'd be better to set the [`HTTPShouldHandleCookies`](https://developer.apple.com/documentation/foundation/nsmutableurlrequest/1415485-httpshouldhandlecookies?language=objc) property on the `NSURLRequest` to false by default. 

Happy to contribute a PR to this effect if you think it's a good idea!

**Comment by mathieudutour** [comment]
Oh I didn't know.

Yes a PR would be great! Could we also handle sending cookies automatically if the `credentials ` option is provided?

**Comment by kannonboy** [comment]
Sounds good! Will do.

**Comment by mathieudutour** [comment]
fixed in 0.3.4
